allowBuilds:
  "@mongodb-js/zstd": true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  node-liblzma: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
trustPolicyExclude:
  - "effect@4.0.0-beta.62"
  - "semver@6.3.1"
